version: "3.5"
services:
  main:
    tty: true
    stdin_open: true
    build:
      context: .
    volumes: 
      - ./results:/app/results
    command: [python, main.py, "--log", "DEBUG", "./tests/SE_PMO_DEZ_2020/pddd_6p.txt", "./tests/SE_PMO_DEZ_2020/pl_6p.txt"]
    # command: [python, main.py, "./tests/entrada_multi_pl.txt", "./tests/entrada_multi_pdde.txt", "./tests/entrada_multi_pdde_cvar.txt"]
    environment: 
      - CONFIG_FILE=./configs/1uhe_tree.json