version: "3.5"
services:
  main:
    tty: true
    stdin_open: true
    build:
      context: .
    volumes: 
      - ./results:/app/results
    environment: 
      - CONFIG_FILE=./configs/1uhe_tree.json