version: "3.5"
services:
  main:
    tty: true
    stdin_open: true
    build:
      context: .
    volumes: 
      - ./results:/app/results
    command: [
          python, 
          main.py,
          "--log",
          "INFO",
          "./tests/exemplos/EX_PDDD.txt",
          "./tests/exemplos/EX_PDDE.txt",
          "./tests/exemplos/EX_PDDE_CVAR1.txt",
          "./tests/exemplos/EX_PDDE_CVAR2.txt",
          "./tests/exemplos/EX_PDDE_CVAR3.txt",
          "./tests/exemplos/EX_PDDE_CVAR4.txt",
          "./tests/exemplos/EX_PDDE_CVAR5.txt",
          "./tests/exemplos/EX_PL_PIOR.txt"
    ]
    # command: [
    #           python, 
    #           main.py,
    #           "--log",
    #           "INFO",
    #           # "./tests/PMO_DEZ_2020/SE/PL_SE_4P.txt",
    #           "./tests/PMO_DEZ_2020/SE/PDDD_SE_4P.txt",
    #           "./tests/PMO_DEZ_2020/SE/PDDE_SE_4P.txt",
    #           # "./tests/PMO_DEZ_2020/SE/PDDE_CVAR_SE_1.txt",
    #           # "./tests/PMO_DEZ_2020/SE/PDDE_CVAR_SE_2.txt",
    #           # "./tests/PMO_DEZ_2020/SE/PDDE_CVAR_SE_3.txt",
    #           # "./tests/PMO_DEZ_2020/SE/PDDE_CVAR_SE_4.txt",
    #           # "./tests/PMO_DEZ_2020/SE/PDDE_CVAR_SE_5.txt",
    #           # "./tests/PMO_DEZ_2020/SE/PDDD_PIOR_SE_4P.txt"
    #           ]
